name: Run RecTV Script and Push to MAN NORMAL TV 2025/rec

on:
  workflow_dispatch:

jobs:
  run-rectv:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Clone Private Py Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/zerodayip/Py.git private_py

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiofiles requests

      - name: Run RecTV Script
        run: python private_py/rectv/rectv.py

      # ✅ Sadece MAN NORMAL TV 2025/rec klasörüne push
      - name: Clone Private MAN NORMAL TV 2025 Repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/nigelhayes11/MAN NORMAL TV 2025.git private_m3u8file

      - name: Copy RecTV m3u files to m3u8file/rec
        run: |
          mkdir -p private_m3u8file/rec
          cp r/reccanli.m3u private_m3u8file/rec/ || echo "reccanli.m3u kopyalanamadı"
          cp r/recfilm.m3u private_m3u8file/rec/ || echo "recfilm.m3u kopyalanamadı"
          cp r/recdizi.m3u private_m3u8file/rec/ || echo "recdizi.m3u kopyalanamadı"
          cp r/recanime.m3u private_m3u8file/rec/ || echo "recanime.m3u kopyalanamadı"

      - name: Commit and Push to MAN NORMAL TV 2025/rec
        run: |
          cd private_m3u8file
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add temp/MAN NORMAL TV 2025.m3u 
          git commit -m "RecTV çıktıları temp klasörüne güncellendi [auto]" || echo "No changes"
          git push origin main
